# Generated by Django 4.2.10 on 2026-06-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_user_id",
                    models.BigIntegerField(verbose_name="Telegram user ID"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_debt", "Create debt"),
                            ("update_debt", "Update debt"),
                            ("close_debt", "Close debt"),
                            ("create_payment", "Create payment"),
                            ("create_income", "Create income"),
                            ("create_expense", "Create expense"),
                            ("show_summary", "Show summary"),
                            ("show_debts", "Show debts"),
                            ("show_payments", "Show payments"),
                            ("show_upcoming_payments", "Show upcoming payments"),
                            ("show_income", "Show income"),
                            ("show_expenses", "Show expenses"),
                            ("ask_clarification", "Ask clarification"),
                            ("no_action", "No action"),
                        ],
                        max_length=32,
                        verbose_name="action type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="payload"),
                ),
                (
                    "llm_raw_response",
                    models.TextField(blank=True, verbose_name="LLM raw response"),
                ),
                (
                    "user_message",
                    models.TextField(blank=True, verbose_name="user message"),
                ),
                (
                    "user_facing_summary",
                    models.TextField(blank=True, verbose_name="user-facing summary"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                ("confidence", models.FloatField(default=0, verbose_name="confidence")),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="executed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot action",
                "verbose_name_plural": "Bot actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(verbose_name="Telegram user ID"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=16,
                        verbose_name="direction",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bot message",
                "verbose_name_plural": "Bot messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
