[pytest]
DJANGO_SETTINGS_MODULE = config.settings.local
python_files = tests.py test_*.py *_tests.py
pythonpath = personal_ai_finance_assistant
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning
