# Generated by Django 4.2.10 on 2026-06-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("openrouter", "OpenRouter")],
                        max_length=32,
                        verbose_name="provider type",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="API key"
                    ),
                ),
                ("base_url", models.URLField(blank=True, verbose_name="base URL")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "LLM provider",
                "verbose_name_plural": "LLM providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LLMSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_tier",
                    models.CharField(
                        choices=[
                            ("free_or_cheap", "Free or cheap"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                            ("custom", "Custom"),
                        ],
                        default="free_or_cheap",
                        max_length=32,
                        verbose_name="active tier",
                    ),
                ),
                (
                    "custom_model_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="custom model ID"
                    ),
                ),
                (
                    "use_rotation_for_openrouter_free_models",
                    models.BooleanField(
                        default=True,
                        verbose_name="use rotation for OpenRouter free models",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(default=2, verbose_name="max retries"),
                ),
                (
                    "temperature",
                    models.FloatField(default=0, verbose_name="temperature"),
                ),
                (
                    "active_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llm.llmproviderconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM settings",
                "verbose_name_plural": "LLM settings",
            },
        ),
        migrations.CreateModel(
            name="LLMModelPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                ("model_id", models.CharField(max_length=255, verbose_name="model ID")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free_or_cheap", "Free or cheap"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                            ("custom", "Custom"),
                        ],
                        default="free_or_cheap",
                        max_length=32,
                        verbose_name="tier",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=100, verbose_name="priority"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_presets",
                        to="llm.llmproviderconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM model preset",
                "verbose_name_plural": "LLM model presets",
                "ordering": ["provider", "tier", "priority", "label"],
            },
        ),
    ]
