# Generated by Django 4.2.10 on 2026-06-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit card"),
                            ("loan", "Loan"),
                            ("installment", "Installment"),
                            ("personal_debt", "Personal debt"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="debt type",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="principal amount",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="current balance"
                    ),
                ),
                (
                    "next_payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="next payment amount",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next payment date"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="interest rate",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="lender name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt",
                "verbose_name_plural": "Debts",
                "ordering": ["next_payment_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="currency"
                    ),
                ),
                ("spent_at", models.DateField(verbose_name="spent at")),
                ("category", models.CharField(max_length=255, verbose_name="category")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-spent_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="currency"
                    ),
                ),
                ("received_at", models.DateField(verbose_name="received at")),
                ("source", models.CharField(max_length=255, verbose_name="source")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Income",
                "ordering": ["-received_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="currency"
                    ),
                ),
                ("paid_at", models.DateField(verbose_name="paid at")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("required_payment", "Required payment"),
                            ("early_repayment", "Early repayment"),
                            ("interest", "Interest"),
                            ("fee", "Fee"),
                            ("other", "Other"),
                        ],
                        default="required_payment",
                        max_length=32,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=255, verbose_name="source"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "reduce_debt_balance",
                    models.BooleanField(
                        default=True, verbose_name="reduce debt balance"
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
    ]
